require_relative "../lib/air-quality-index-with-api/version"
require_relative "../lib/air-quality-index-with-api/cli"
require_relative "../lib/air-quality-index-with-api/local_aqi"
require_relative "../lib/air-quality-index-with-api/nationwide_aqi"
require_relative "../lib/air-quality-index-with-api/aqi_info"
require_relative "../lib/air-quality-index-with-api/city"
