require_relative "../lib/air_quality_index/version"
require_relative "../lib/air_quality_index/cli"
require_relative "../lib/air_quality_index/local_aqi"
require_relative "../lib/air_quality_index/nationwide_aqi"
require_relative "../lib/air_quality_index/aqi_info"
require_relative "../lib/air_quality_index/city"
